using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TextLogList : MonoBehaviour {

	public static Dictionary<string, string> dialoguesList = new Dictionary<string, string> {
		{ "medic", "Medic log #5892\n\nI never thought cryosleep could last so long. In theory, waking time can vary from person to person since it depends on a lot of different biological mechanisms, so it's to be expected. But I've noticed three individuals who show no signs of waking up anytime soon. We don't have enough people in our staff and it will to be a problem in the remaining years since we have no clue whether we're ever going back home. I guess it's time we should call this ship our tiny little world."},
		{ "security", "Security log #7381\n\nI believe there's a serious problem with our emergency plan. If something happens and we need to go to the escape pods and abandon ship, we would need clearance from the control room in order to unlock the doors. But the only one with access to the control room is the captain. If something happens to him, I don't know how we could abandon ship safely. I wonder why nobody thought about this before and why so much power is centered in the hands of one single man. I'm going to file a report to Central."},
		{ "electrician", "Electrician log #3942\n\nThere's something wrong with the elevator's wires that makes the fuse fall all the time. I can't see why. Maybe there's something involving the guys from the kitchen above the generator. Their oven demands an aburd amound of eletrical power, so I think we should check that out. We also need a better way for collecting solar power if we want to stay alive in this tin can. The folks from the research department are demanding more and more power everyday, if only they could tell us what the hell they're doing, it would make our jobs whole lot easier."},
		{ "cooker", "Cooker Log #1789\n\nFood supplies are running out. We should talk with the smartasses at the research lab to figure out what we're going to do. Maybe begin some sort of plantation, I don't know. Hell, never thought I would spend the rest of my days in a ship in deep space. Should we call this place home now?"},
		{ "captain", "Captain Log # 4238\n\nThings are getting tougher and tougher. Central won't answer our calls to return so I guess we have to stay here until second orders arrive. The crew is getting more and more anxious with the perspective of living here. The individuals still in cryosleep are also another issue I have to work on, and there's also the Research Lab \"crysis\" which I also have to solve. It's too much burden for just one man. Our world looks so small through my window, I miss it very much."},
		{ "scientist", "Scientist Log # 6059\n\nThe experiment was a success. It's very fortunate that I was allowed to work with full discretion. Not having to worry about crew's opinions in my experiment is the best possible scenario. Central invented a situation for the crew and their families to believe they have to stay here, so that's also fine. I believe none of them will survive the virus. There is one subject in cryosleep who is developing some sort of bond with the virus and might just be able to survive the process. I will set the ship to autodestruction mode for when the subject wakes up, so that there's no trace of what I was doing here. When the subject gets to our planet we shall keep on examining and experimenting with the body and the virus. The subject's body shall be the virus small world from now on."},
	};

}
